# Generated by Django 5.2.5 on 2026-07-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_voicecampaignresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemediafile',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
    ]
