# Generated by Django 5.2.5 on 2026-07-18 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_voicemediafile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCallDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('call_date', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('service_no', models.CharField(blank=True, max_length=20)),
                ('obd_campaign_name', models.CharField(blank=True, max_length=255)),
                ('dial_time', models.CharField(blank=True, max_length=40)),
                ('answered_time', models.CharField(blank=True, max_length=40)),
                ('end_time', models.CharField(blank=True, max_length=40)),
                ('duration_secs', models.IntegerField(default=0)),
                ('call_status', models.CharField(blank=True, max_length=20)),
                ('call_flow', models.CharField(blank=True, max_length=50)),
                ('disposition', models.CharField(blank=True, max_length=100)),
                ('retry', models.IntegerField(default=0)),
                ('pulse', models.IntegerField(default=0)),
                ('cost', models.CharField(blank=True, max_length=20)),
                ('dtmf_input', models.CharField(blank=True, max_length=10)),
                ('prompt_length', models.CharField(blank=True, max_length=10)),
                ('tts_count', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='api.voicecampaign')),
            ],
            options={
                'unique_together': {('mobile', 'dial_time', 'obd_campaign_name')},
            },
        ),
    ]
