# Generated by Django 5.2.5 on 2026-07-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_voicecalldisposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicecampaign',
            name='no_answer',
            field=models.IntegerField(default=0),
        ),
    ]
